version: '3'

services:
  # Apache and PHP
  
  web:
    build:
      context: ./php
    volumes:
      - ./MembershipM-PHP:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  # MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: membershiphp
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_HOST: db
    ports:
      - "3306:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
